#!/usr/bin/env php
<?php

// set to run indefinitely if needed
set_time_limit(0);
date_default_timezone_set('Europe/Copenhagen');

// include the composer autoloader
require_once __DIR__ . '/../vendor/autoload.php';

// import the Symfony Console Application
use Symfony\Component\Console\Application;
use zsim0n\JyskeBank\GoogleCommand;
use zsim0n\JyskeBank\YnabCommand;

$app = new Application();
$app->add(new GoogleCommand());
$app->add(new YnabCommand());
$app->run();
